config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#top'
  devise_for :users
  resources :users, only: [:create, :index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  get'/home/about' => 'home#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    
      validates :title, presence: true
      validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, uniqueness: { case_sensitive: false }, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  
    def get_profile_image(width, height)
        unless profile_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        profile_image.variant(resize_to_limit: [width, height]).processed
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  
    before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

 add_flash_types :success, :info, :warning, :danger

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :edit      
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  protected
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to books_path, notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to user_path(current_user.id), notice: 'You have updated user successfully.'
        else
          render :edit      
        end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book2_helper.rb
module Book2Helper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <table class="table">
    <tbody>
      <%= image_tag @user.get_profile_image(100,100) %>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class ="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: Book.new do |f| %>
    <div class="form-group">
      <%= f.label :Title %><br/>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :Opinion %><br/>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/_list_show.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: Book.new do |f| %>
    <div class="form-group">
      <%= f.label :Title %><br/>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :Opinion %><br/>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		    <h1>Editing Book</h1>
		    <div id="error_explanation">
		      <% if @book.errors.any? %>
            <h2>
              <%= @book.errors.count %> errors prohibited this obj from being saved:
            </h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <%= form_with model: @book do |f| %>
          <div  class="form-group">
            <%= f.label :Title %><br />
            <%= f.text_field :title, class:" form-control" %>
          </div>
          <div  class="form-group">
            <%= f.label :Opinion %><br />
            <%= f.text_area :body, class:" form-control" %>
          </div>
          <div  class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>
	    
	      <%= link_to 'Show', book_path(@book.id) %>|
	      <%= link_to 'Back', books_path %>
	   </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <%= flash[:notice] %>
    <div id="error_explanation">
      <% if @book.errors.any? %>
        <h2>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %> 
    </div>
    <div class="row">
      <%= render 'list', books: @books %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag book.user.get_profile_image(90,90) %><br/>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <table class="table">
          <tbody>
            <%= image_tag @user.get_profile_image(100,100) %>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @book.user.introduction %></th>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@book.user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class ="fas fa-user-cog"></i>
          <% end %>
        </div>
        <%= render 'list_show', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td class= "font-weight-normal">
                <%= link_to user_path(@book.user.id) do %>
                  <%= image_tag @book.user.get_profile_image(100,100) %><br/>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
              <td>
                <%= link_to edit_book_path(@book.id), class: 'btn btn-success btn-sm' do %>
                  Edit
                <% end %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, class:'btn btn-danger btn-sm', data: {confirm: "本当に消しますか？"} %>
              </td>
              <% end %>
            </tr>
          </tbody>
        </table>          
      </div>
    </div>
</main>

app/views/home/about.html.erb
<main>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
</main>

app/views/home/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1", "maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">  
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
            <div class="collapse navbar-collapse">
              <% if user_signed_in? %>
                <ul class="navbar-nav ml-auto">
                  <li class= "nav-item mr-3">
                    <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                      <i class="fas fa-home"></i> Home
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to users_path, class: "nav-link text-light" do %>
                      <i class="fas fa-users"></i> Users
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                      <%= link_to books_path, class: "nav-link text-light" do %>
                        <i class="fas fa-book-open"></i> Books
                      <% end %>
                    </li>
                  <li class="nav-item mr-3">
                    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                      <i class="fas fa-sign-out-alt"></i> Log out
                    <% end %>
                  </li>
                </ul>
              <% else %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-3">
                    <%= link_to root_path, class: "nav-link text-light" do %>
                      <i class="fas fa-home"></i> Home
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to about_path, class: "nav-link text-light" do %>
                      <i class= "inline fas fa-link"></i> About
                     <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                      <i class="fas fa-user-plus"></i> Sign up
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                      <i class="fas fa-sign-in-alt"></i> Log in
                    <% end %>
                  </li>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
      
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class ="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h2>
              <%= @user.errors.count %> errors prohibited this obj from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          </div>
          <%= form_with model: @user do |f| %>
	          <div  class="form-group">
              <%= f.label :Name %><br />
              <%= f.text_field :name, class:" form-control" %>
            </div>
            <div  class="form-group">
              <%= f.label :Image %><br />
              <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept:"image/*" %>
            </div>
            <div  class="form-group">
              <%= f.label :Introduction %><br />
              <%= f.text_area :introduction, class:" form-control" %>
            </div>
            <div  class="form-group">
              <%= f.submit "Update User", class: "btn btn-secondary" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/list', books: @books %>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(user.id) do %>
                  <%= image_tag user.get_profile_image(90,90) %><br/>
                <% end %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to user_path(user.id) do %>
                  Show
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <table class="table">
          <tbody>
            <%= image_tag @user.get_profile_image(100,100) %>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class ="fas fa-user-cog"></i>
          <% end %>
        </div>
        <%= render 'books/list_show', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
              <% @books.each do |book| %>
            <tbody>
              <tr>
                <th>
                  <%= link_to user_path(@user.id) do %>
                    <%= image_tag @user.get_profile_image(90,90) %><br/>
                  <% end %>
                </th>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
            </tbody>
            <% end %>
          </table>          
      </div>
  </div>
</main>